config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, :controllers => {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }


  namespace :item do
   get 'buys/sort'
   get 'buys/search'
   get 'buys/category'
   resources :buys do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
   end
  end

  namespace :item do
   get 'sells/:id/complete',to: 'sells#complete',as: 'sells_complete'
   resources :sells do
   end
  end


  namespace :item do
   get 'homes/sort'
   get 'homes/search'
   get 'homes/category'
   resources :homes
  end

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]


  get 'orders/complete'
  post 'orders/confirm'
  resources :orders, only: [:new, :index, :show, :create]

  put "/customers/:id/withdraw" => "customers#withdraw", as: 'customers_withdraw'
  get 'customers/unsubscribe'
  resources :customers, only: [:show, :edit, :update]


  root to: 'item/buys#index'
  get 'homes/about'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :category_id, presence: true
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9999999}

  has_one :order
  belongs_to :item_home, optional: true
  belongs_to :category
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :image
  enum order_status: {unknown: 0, sale: 1, purchased: 2}

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end


  def self.looks(search, word, sale_status)
    if search == "perfect_match"
      @item = Item.where("name LIKE?","#{word}").where(order_status: sale_status)
    elsif search == "forward_match"
      @item = Item.where("name LIKE?","#{word}%").where(order_status: sale_status)
    elsif search == "backward_match"
      @item = Item.where("name LIKE?","%#{word}").where(order_status: sale_status)
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%").where(order_status: sale_status)
    else
      @item = Item.all
    end
  end
end

app/models/item/sell.rb
class Item::Sell < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :body, presence: true

  belongs_to :customer
  attachment :image
end

app/controllers/item/buys_controller.rb
class Item::BuysController < ApplicationController
  def index
    @items = Item.where(is_deleted: false)
    @q = Item.ransack(params[:q])
  end

  def new
    @item = Item.new
    @category_parent = Category.where("ancestry is null")
  end


  def create
    @item = Item.new(item_params)
    @item.customer_id = current_customer.id
    if @item.save
      redirect_to item_sells_complete_path(@item)
    else
      render :new
    end
  end

  def sort
    @q = Item.ransack(params[:q])
    selection = params[:keyword]
    @items = Item.sort(selection,params[:word],params[:search])
  end

  def search
    @q = ItemHome.ransack(params[:q])
    @items = Item.looks(params[:search], params[:word], params[:sale_status])
    @items = sort_at(@items,params[:keyword])
  end

  def category
    @q = Item.ransack(params[:q])
    @items = @q.result
    category_id = params[:q][:category_id_eq]
    @category = Category.find_by(id: category_id)
  end


  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
    @customer = @item.customer
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_buy_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :category_id, :customer_id, :keyword)
  end


  def search_category_item
    @q = Item.ransack(params[:q])
  end

  def sort_at(items, selection)
    case selection
    when 'new'
      return items.where(is_deleted: false).order(created_at: :DESC)
    when 'old'
      return items.where(is_deleted: false).order(created_at: :ASC)
    when 'likes'
      # likes > 0
      array1 = items.where(is_deleted: false).where(id: Favorite.group(:item_id).order(Arel.sql('count(item_id) desc')).pluck(:item_id)).where(is_deleted: false)
      # likes = 0
      array2 = items.where(is_deleted: false) - where(id: Favorite.group(:item_id).pluck(:item_id)).where(is_deleted: false)
      return array1 + array2
      #return where(id: Favorite.group(:item_id).order(Arel.sql('count(item_id) desc')).pluck(:item_id)).where(is_deleted: false)
    when 'dislikes'
      array1 = items.where(is_deleted: false). - where(id: Favorite.group(:item_id).pluck(:item_id)).where(is_deleted: false)
      array2 = items.where(is_deleted: false).where(id: Favorite.group(:item_id).order(Arel.sql('count(item_id) asc')).pluck(:item_id)).where(is_deleted: false)
      return array1 + array2
    when 'high'
      return items.where(is_deleted: false).order(price: :DESC)
    when 'low'
      return items.where(is_deleted: false).order(price: :ASC)
    end
  end

end

app/controllers/item/comments_controller.rb
class Item::CommentsController < ApplicationController
  def create
    item = Item.find(params[:buy_id])
    comment = current_customer.comments.new(comment_params)
    comment.item_id = item.id
    comment.save
    redirect_to item_buy_path(item.id)
  end


  def destroy
    Comment.find_by(id: params[:id]).destroy
    redirect_to item_buy_path(params[:buy_id])
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/item/favorites_controller.rb
class Item::FavoritesController < ApplicationController
  def create
    item = Item.find(params[:buy_id])
    favorite = current_customer.favorites.new(item_id: item.id)
    favorite.save
    redirect_to item_buy_path(item.id)
  end

  def destroy
    item = Item.find(params[:buy_id])
    favorite = current_customer.favorites.find_by(item_id: item.id)
    favorite.destroy
    redirect_to item_buy_path(item.id)
  end
end

app/controllers/item/homes_controller.rb
class Item::HomesController < ApplicationController
  before_action :correct_user, only: [:show, :destroy, :edit, :update]
  def index
    @homes = ItemHome.all.where(customer_id: current_customer.id)
    @q = ItemHome.ransack(params[:q])
  end

  def new
    @home = ItemHome.new
    @category_parent = Category.where("ancestry is null")
  end

  def create
    @home = ItemHome.new(home_params)
    @home.customer_id = current_customer.id
    #@item.order_status = :unknown
    if @home.save
      redirect_to item_homes_path
    else
      render :new
    end
  end

  def sort
    @q = ItemHome.ransack(params[:q])
    selection = params[:keyword]
    @homes = ItemHome.sort(selection,params[:word],params[:search]).where(customer_id: current_customer.id)
  end

  def search
    @q = ItemHome.ransack(params[:q])
    @homes = ItemHome.looks(params[:search], params[:word]).where(customer_id: current_customer.id)
  end

  def show

    @home = ItemHome.find(params[:id])
    @item = Item.find_by(item_home_id: @home.id)
  end


  def category
    @q = ItemHome.ransack(params[:q])
    @homes = @q.result.where(customer_id: current_customer.id)
    category_id = params[:q][:category_id_eq]
    @category = Category.find_by(id: category_id)
  end

  def edit
    @home = ItemHome.find(params[:id])
  end

  def update
    @home = ItemHome.find(params[:id])
    if @home.update(home_params)
      redirect_to item_home_path(@home)
    else
      render :edit
    end
  end

  def destroy
    @home = ItemHome.find(params[:id])
    @home.destroy
    redirect_to item_homes_path
  end

  private
  def home_params
    params.require(:item_home).permit(:name, :image, :introduction, :place_to_put, :category_id)
  end

  def search_category_item
    @q = ItemHome.ransack(params[:q])
  end

  def correct_user
    @home = ItemHome.find(params[:id])
    @homes = ItemHome.all.where(customer_id: current_customer.id)
    if !@homes.include?(@home)
      redirect_to root_path
    end
  end
end

app/controllers/item/sells_controller.rb
class Item::SellsController < ApplicationController
  def index
    @items = Item.all.where(customer_id: current_customer.id, is_deleted: false)
  end


  def new
    if home_item_id = params[:home_item_id]
      @home_item = ItemHome.find(home_item_id)
      @item = Item.new(name: @home_item.name, introduction: @home_item.introduction, category_id: @home_item.category_id)
      if Item.where(item_home_id: home_item_id).size > 0
        @item = Item.where(item_home_id: home_item_id).first
      end
    else
      @item = Item.new
    end
    @category_parent = Category.where("ancestry is null")
  end

  # def category_children
  #   @category_children = Category.find("#{params[:parent_id]}").children
  # end

  # def category_grandchildren
  #   @category_grandchildren = Category.find("#{params[:child_id]}").children
  # end

  def create
    if !params[:item][:item_home_id].blank? && Item.where(item_home_id: params[:item][:item_home_id]).size > 0
      @item = Item.find_by(item_home_id: params[:item][:item_home_id])
      @item.name = params[:item][:name]
      @item.image = params[:item][:image]
      @item.introduction = params[:item][:introduction]
      @item.price = params[:item][:price]
      @item.category_id = params[:item][:category_id]
      @item.customer_id = params[:item][:customer_id]
    else
      @item = Item.new(item_params)
    end
    @item.order_status = :sale
    @item.customer_id = current_customer.id
    if @item.save
      redirect_to item_sells_complete_path(@item)
    else
      render :new
    end
  end

  def complete
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def destroy
    @item = Item.find(params[:id])
    @item.update(is_deleted: true, order_status: :unknown)
    redirect_to item_buys_path
  end


  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :category_id, :customer_id, :item_home_id)
  end

end

app/helpers/item/buys_helper.rb
module Item::BuysHelper
end

app/helpers/item/comments_helper.rb
module Item::CommentsHelper
end

app/helpers/item/homes_helper.rb
module Item::HomesHelper
end

app/helpers/item/sells_helper.rb
module Item::SellsHelper
end

app/views/item/buys/_index.html.erb
<div class="container px-5 px-sm-0 card-list-container py-5">
  <div class="row">
    <div class="col-md-3">
      <div class="sticky">
        <h2>検索ページ</h2>
        <%= form_with url: item_buys_search_path, local: true, method: :get do |f| %>
          <%= f.text_field :word, class:"form-group" %><br>
          <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backword_match"], ["部分一致","partial_match"]]), class:"form-group" %><br>
          <%= f.select :sale_status, options_for_select([["出品中","sale"], ["購入済み","purchased"]]) %><br>
          <%= f.select :keyword, [['投稿が新しい順', 'new'], ['投稿が古い順', 'old'], ['いいねが多い順', 'likes'], ['いいねが少ない順', 'dislikes'], ['価格が高い順', 'high'], ['価格が低い順', 'low']], class:"form-group"%><br>
          <%= f.submit "ワード検索", class:"btn btn-success center-block btn-block" %>
        <% end %>
        <h2></h2>
        <h4>カテゴリー検索</h4>
        <%= search_form_for @q, url: item_buys_category_path do |f| %>
          <%= f.collection_select :category_id_eq, Category.where(ancestry: nil), :id, :name, include_blank: "カテゴリー検索", class:"form-group" %>
          <%= f.submit 'カテゴリー検索', class:"btn btn-success center-block btn-block"%>
        <% end %>
      </div>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-8 offsset-md-1">
      <div class="flex-container">
        <% @items.each do |item| %>
          <div class="card col-lg-4 col-md-2 mb-4">
            <div style="text-align: center">
              <%= link_to item_buy_path(item), class:"text-dark" do %>
                <%= attachment_image_tag item, :image, :fill, 200, 200 %>
              <% end %><br>
              <strong><span><%= item.name %></span></strong><br>
              <span><%= number_to_currency(item.price) %></span><br>
              <% if item.order_status == 'sale' %>
                <%= item.order_status_i18n %>
              <% else item.order_status == 'purchased' %>
                <%= item.order_status_i18n %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/item/buys/category.html.erb
<%#= render 'item/buys/category', q: @q %>
<%= render 'item/buys/index', items: @items %>

app/views/item/buys/index.html.erb
<%#= render 'item/buys/category', q: @q %>
<%= render 'item/buys/index', items: @items %>

app/views/item/buys/search.html.erb
<%#= render 'item/buys/category', q: @q %>
<%= render 'item/buys/index', items: @items %>

app/views/item/buys/show.html.erb
<div class="container p-5 px-sm-0">
  <div class="row">
    <div class="col-md-5">
      <div class="sticky">
        <h2>購入商品詳細</h2>
        <%= attachment_image_tag @item, :image, :fill, 400, 400, class:"form-group" %>
        <% if @item.order_status == 'purchased' %>
        <% elsif (@customer.id != current_customer.id) && (@item.order_status == 'sale') %>
          <%= link_to '購入手続きへ', new_order_path(sell_id: @item.id), class:"btn btn-success btn-block px-5"%>
        <% end %>
        <% if (@customer.id == current_customer.id) && (@item.order_status == 'sale') %>
          <%= link_to '編集する',  edit_item_sell_path(@item), class:"btn btn-success btn-lg center-block" %>
          <%= link_to "出品を取りやめる", item_sell_path(@item), method: :delete, data:{confirm: "出品を取りやめますか？"}, class:"btn btn-danger btn-lg center-block" %>
        <% end %>
      </div>
    </div>
    <div class="col-md-7">
      <table class="item-buy-table col4t th-nowrap" style="font-size: 20px; width: 100%">
        <thead>
          <tr>
            <th>商品名</th>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <th>出品額</th>
            <td><%= number_to_currency(@item.price) %></td>
          </tr>
           <tr>
            <th>商品説明</th>
            <td class:"word-wrap: break-word"><%= @item.introduction %></td>
          </tr>
          <tr>
            <th>出品者名</th>
            <td><%= @item.customer.last_name %><%= @item.customer.first_name %></td>
          </tr>
           <tr>
            <th>商品カテゴリー</th>
            <td><%= @item.category.name %></td>
          </tr>
          <tr>
            <th>いいね</th>
            <td>
              <% if @item.favorited_by?(current_customer) %>
                <div>
                  <%= link_to item_buy_favorites_path(@item), method: :delete do %>
                    ♥<%= @item.favorites.count %> いいね
                  <% end %>
                </div>
              <% else %>
                <div>
                  <%= link_to item_buy_favorites_path(@item), method: :post do %>
                    ♡<%= @item.favorites.count %> いいね
                  <% end %>
                </div>
              <% end %>
            </td>
          </tr>
          <tr>
            <th>出品日時</th>
            <td><%= @item.created_at.strftime("%Y年%m月%d日%H時%M分") %></td>
          </tr>
          <tr>
            <th>コメント</th>
            <td>コメント件数：<%= @item.comments.count %></td>
          </tr>
          <% @item.comments.each do |comment| %>
            <tr>
              <% if comment.customer.id == @item.customer.id %>
                <th class="buy-customer-color"><%= comment.customer.last_name %><%= comment.customer.first_name %></th>
              <% else %>
                <th class="colored"><%= comment.customer.last_name %><%= comment.customer.first_name %></th>
              <% end %>
              <td>
                <%= comment.comment %><br>
                <%= comment.created_at.strftime('%Y/%m/%d') %>
                <% if comment.customer == current_customer %>
                  <%= link_to "削除", item_buy_comment_path(comment.item, comment), method: :delete %>
                <% end %>
                <br>
              </td>
              </tr>
          <% end %>
        </thead>
      </table>
      <div>
        <% if @item.order_status == 'sale' %>
          <%= form_with(model:[@item, @comment], url: item_buy_comments_path(@item.id), local: true) do |f| %>
            <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class:"width: 100%;" %><br>
            <%= f.submit "コメントを送信する", class:"btn btn-success  center-block" %>
          <% end %>
        <% else @item.order_status == 'purchased' %>
          <p>※売り切れのためコメントできません</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/item/buys/sort.html.erb
<%#= render 'item/buys/category', q: @q %>
<%= render 'item/buys/index', items: @items %>