config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, :controllers => {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }


  namespace :item do
   get 'buys/sort'
   get 'buys/search'
   get 'buys/category'
   resources :buys do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
   end
  end

  namespace :item do
   get 'sells/:id/complete',to: 'sells#complete',as: 'sells_complete'
   resources :sells do
   end
  end


  namespace :item do
   get 'homes/sort'
   get 'homes/search'
   get 'homes/category'
   resources :homes
  end

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]


  get 'orders/complete'
  post 'orders/confirm'
  resources :orders, only: [:new, :index, :show, :create]

  put "/customers/:id/withdraw" => "customers#withdraw", as: 'customers_withdraw'
  get 'customers/unsubscribe'
  resources :customers, only: [:show, :edit, :update]


  root to: 'item/buys#index'
  get 'homes/about'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :telephone_number, presence: true


  has_many :items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :comments, dependent: :destroy
  # has_many :images, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
  #退会したユーザーをログインできなくする


end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_customer
    @customer = Customer.find_by(email: params[:customer][:email].downcase)
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.active_for_authentication? == false))
        puts '='*20
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    if  @customer.update(customer_params)
      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end

  def unsubscribe
    @customer = current_customer
  end

  def withdraw
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :password, :password_confirmation)
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container p-5 px-sm-0 py-5">
  <% if @customer.errors.any? %>
  <ul style="color: red">
    <%= @customer.errors.count %>件のエラーが発生しました
    <% @customer.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  </ul>
  <% end %>
  <h2>会員情報編集</h2>

  <%= form_with model: @customer, url: customer_path(@customer), local:true do |f| %>
    <table class="customer-table" style="font-size: 20px;">
      <tr>
        <th><%= f.label "名前", class:"form-group" %></th>
        <td>
          <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name", class:"form-group" %>
          <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name",class:"form-group" %>
        </td>
      </tr>
      <tr>
        <th><%= f.label "フリガナ", class:"form-group" %></th>
        <td>
          <%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana",class:"form-group"  %>
          <%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana", class:"form-group" %>
        </td>
      </tr>
      <tr>
        <th><%= f.label "メールアドレス", class:"form-group" %></th>
        <td><%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-group" %></td>
      </tr>
      <tr>
        <th><%= f.label "郵便番号（ハイフンなし）", class:"form-group" %></th>
        <td><%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code", class:"form-group" %></td>
      </tr>
      <tr>
        <th><%= f.label "住所", class:"form-group" %></th>
        <td><%= f.text_field :address, autofocus: true, autocomplete: "address", :value_method => :name, include_blank: '都道府県',class:"form-group" %></td>
      </tr>
      <tr>
        <th><%= f.label "電話番号（ハイフンなし）", class:"form-group" %></th>
        <td><%= f.text_field :telephone_number, autofocus: true, autocomplete: "phone_number",class:"form-group" %></td>
      </tr>
      <tr>
        <th><%= f.label "パスワード（６文字以上）", class:"form-group" %></th>
        <td><%= f.password_field :password, autocomplete: "new-password", class:"form-group" %>
        </td>
      <tr>
        <th><%= f.label "パスワード（確認用）", class:"form-group" %></th>
        <td><%= f.password_field :password_confirmation, autocomplete: "new-password", class:"form-group" %>
      </tr>
    </table>
    <div align="center">
      <%= f.submit "編集内容を保存", class:"btn btn-success btn-lg form-group " %>
      <%= link_to '退会する', customers_unsubscribe_path, class:"btn btn-outline-danger btn-lg form-group" %>
    </div>
  <% end %>

app/views/customers/show.html.erb
<div class="container px-5 px-sm-0 py-5">
  <div row>
    <div col-12>
      <table class="customer-table" style="font-size: 20px; width: 100%">
        <h1>マイページ</h1>
        <h3>登録情報</h3>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>カナ</th>
          <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td>〒<%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= link_to 'プロフィールを編集する', edit_customer_path(@customer), class:"btn btn-success btn-lg center-block" %></td>
        </tr>
        <tr>
          <th></th>
          <td><%= link_to '配送先一覧を見る', addresses_path, class:"btn btn-success btn-lg center-block" %></td>
        </tr>
        <tr>
          <th></th>
          <td>
            <% if @customer.orders.present? %>
              <%= link_to '購入商品履歴一覧を見る', orders_path, class:"btn btn-success btn-lg center-block" %>
            <% else %>
              購入商品はありません
            <% end %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <% if @customer.items.present? %>
              <%= link_to '出品した商品を確認する', item_sells_path, class:"btn btn-success btn-lg center-block" %>
            <% else %>
              出品商品はありません
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/customers/unsubscribe.html.erb
<div style="text-align: center" class="my-5 ml-10">
  <h2>本当に退会しますか？</h2>
  <h4>退会すると、会員登録情報や</h4>
  <h4>これまでの購入履歴が閲覧できなくなります。</h4>
  <h4>退会する場合は、「退会する」をクリックしてください。</h4>
  <% if customer_signed_in? && @customer.id == current_customer.id %>
    <%= link_to "退会", customers_withdraw_path(@customer), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-outline-danger btn-lg" %>
    <%= link_to '退会しない', customer_path(current_customer), class: "btn btn-outline-danger btn-lg" %>
  <% end %>
</div>