config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, :controllers => {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }


  namespace :item do
   get 'buys/sort'
   get 'buys/search'
   get 'buys/category'
   resources :buys do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
   end
  end

  namespace :item do
   get 'sells/:id/complete',to: 'sells#complete',as: 'sells_complete'
   resources :sells do
   end
  end


  namespace :item do
   get 'homes/sort'
   get 'homes/search'
   get 'homes/category'
   resources :homes
  end

  resources :addresses, only: [:index, :edit, :create, :update, :destroy]


  get 'orders/complete'
  post 'orders/confirm'
  resources :orders, only: [:new, :index, :show, :create]

  put "/customers/:id/withdraw" => "customers#withdraw", as: 'customers_withdraw'
  get 'customers/unsubscribe'
  resources :customers, only: [:show, :edit, :update]


  root to: 'item/buys#index'
  get 'homes/about'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OKATADUKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100" >
    <header class="shadow-sm" style="background:green;">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container" >
          <div class="d-grid gap-2 d-md-block">
            <%= link_to 'お片付けフリマサイト', item_buys_path, class: 'nav-link text-white' %>
          </div>
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item">
                <%= link_to 'マイページ', customer_path(current_customer), class: 'nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to 'お片付けページ', item_homes_path, class: 'nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to '出品する', new_item_sell_path({item: {home_id: nil}}), class: 'nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-white' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "ABOUT", homes_about_path, class: 'nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-white' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-white' %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
  </body>
</html>